### ISSUE TITLE
GitHub Pages boilerplate generator

### ISSUE THREAD

**Issue by mshick** [planetjekyll/awesome-jekyll#11]
I recently put this comprehensive GitHub Pages / Jekyll boilerplate generator together: [slush-gh-pages](https://github.com/ronik-design/slush-gh-pages). Perhaps you'd be interested in including it on your list? 

I tried to pack a lot into the READMEs to help new users, so hopefully it's a great starting point for anybody using Jekyll.

**Comment by geraldb** [comment]
@mshick  Looks great.  Awesome Jekyll is do-it-yourself (DIY) ;-)  Please add your slush-gh-pages (with a pull request) if interested. Thanks.
